name = "JuliaPackageTemplate"
uuid = "24d2106d-e7e1-4641-aa0a-4a5934943aa1"
version = "0.1.0"

[workspace]
projects = ["test", "docs"]

[deps]

[weakdeps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extensions]
JuliaPackageTemplateTestExt = "Test"

[compat]
Test = "1"
julia = "1.10"
